name: Push Schema Documentation Update

on:
  push:
    paths:
      - docs/github-actions/schema.json

jobs:
  ##############################################################################
  # This section is added so that after every merge, if the
  # docs/github-actions/schema.json is changed, the site should rebuild to
  # to show the changes.
  ##############################################################################

  Push-Workflow:
    name: Updating Schema Documentation
    runs-on: ubuntu-latest
    environment: TALAWA_ENVIRONMENT

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TALAWA_DOCS_SYNC }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Sleep for 10 s
      - name: Sleep for 10s
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s

      - name: Generate the Markdown documentation due to the changed schema
        run: yarn docusaurus graphql-to-doc

      - name: Add the generated Markdown Documentation to stage
        run: git add .

      # We use this action to commit the changes above to the repository
      - name: Commit the changes to the repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add markdown files for the updated schema
